### ISSUE TITLE
Parsing versions given by tags of the form debian/1.9-4 doesn't work

### ISSUE THREAD

**Issue by SnarkBoojum** [pypa/setuptools-scm#402] opened 2020-01-22 15:44 UTC
I have a report [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=933739) on the Debian package about AssertionError exceptions when the tag giving the version is of the form debian/1.9-4.

Can something be done?

**Comment by RonnyPfannschmidt** [comment] 2020-01-22 20:51
duplicate of https://github.com/pypa/setuptools_scm/issues/246

**Closed as completed by RonnyPfannschmidt** 2020-01-22 20:51 UTC

**Comment by matthijskooijman** [comment] 2020-05-04 09:59
I actually think this is *not* a duplicate of #246. That is about the somewhat Debian-sepcific `~` character in version numbers. This report looks like it stems from building from a Debian-packaging-repository (which has upstream sources imported). I suspect so, based on the format of the tag (`debian/1.9.4` is typically something created by the `git-buildpackage` Debian package builder) and the origin of the bug.

I believe the fix for this is not to allow parsing these `debian/...` tags, as could be the subject of #243, but instead to *not* try to parse this git tag at all, as suggested in #423. See also that issue for details about this usecase.

**Comment by RonnyPfannschmidt** [comment] 2020-05-04 10:15
From my pov both of those are in the domain of distribution specify workflows
