### ISSUE TITLE
LookupError: setuptools-scm was unable to detect version (due to no git installation)

### ISSUE THREAD

**Issue by kratsg** [pypa/setuptools-scm#363] opened 2019-10-18 05:24 UTC
Hi,

I'm using this to provide dev versions (which is nice). I have a `.gitlab-ci.yml` configuration like so:

```
package:
  image: python:3.7-alpine
  stage: package
  before_script:
    - python -m pip install pep517 --user
  script:
    - python -m pep517.build --source --binary --out-dir dist/ .
  artifacts:
    paths:
      - dist/
```

for packaging. As it turns out, in the alpine docker images, there is no `git` (not surprising). What is a little misleading is the error message associated with the fact that `git` doesn't exist:

```
$ python -m pep517.build --source --binary --out-dir dist/ .
/tmp/pep517-build-env-6rj6j5_k/lib/python3.7/site-packages/setuptools_scm/utils.py:119: UserWarning: 'git' was not found
  warnings.warn("%r was not found" % name)
Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/pep517/_in_process.py", line 257, in <module>
    main()
  File "/root/.local/lib/python3.7/site-packages/pep517/_in_process.py", line 240, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/root/.local/lib/python3.7/site-packages/pep517/_in_process.py", line 213, in build_sdist
    return backend.build_sdist(sdist_directory, config_settings)
  File "/tmp/pep517-build-env-6rj6j5_k/lib/python3.7/site-packages/setuptools/build_meta.py", line 214, in build_sdist
    config_settings)
  File "/tmp/pep517-build-env-6rj6j5_k/lib/python3.7/site-packages/setuptools/build_meta.py", line 194, in _build_with_temp_dir
    self.run_setup()
  File "/tmp/pep517-build-env-6rj6j5_k/lib/python3.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 87, in <module>
    dependency_links=[],
  File "/tmp/pep517-build-env-6rj6j5_k/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.7/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/tmp/pep517-build-env-6rj6j5_k/lib/python3.7/site-packages/setuptools/dist.py", line 447, in __init__
    k: v for k, v in attrs.items()
  File "/usr/local/lib/python3.7/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/tmp/pep517-build-env-6rj6j5_k/lib/python3.7/site-packages/setuptools/dist.py", line 735, in finalize_options
    ep.load()(self, ep.name, value)
  File "/tmp/pep517-build-env-6rj6j5_k/lib/python3.7/site-packages/setuptools_scm/integration.py", line 17, in version_keyword
    dist.metadata.version = get_version(**value)
  File "/tmp/pep517-build-env-6rj6j5_k/lib/python3.7/site-packages/setuptools_scm/__init__.py", line 150, in get_version
    parsed_version = _do_parse(config)
  File "/tmp/pep517-build-env-6rj6j5_k/lib/python3.7/site-packages/setuptools_scm/__init__.py", line 113, in _do_parse
    "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
LookupError: setuptools-scm was unable to detect version for '/builds/scipp/itkdb'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/.local/lib/python3.7/site-packages/pep517/build.py", line 124, in <module>
    main(parser.parse_args())
  File "/root/.local/lib/python3.7/site-packages/pep517/build.py", line 120, in main
    build(args.source_dir, dist, args.out_dir)
  File "/root/.local/lib/python3.7/site-packages/pep517/build.py", line 88, in build
    _do_build(hooks, env, dist, dest)
  File "/root/.local/lib/python3.7/site-packages/pep517/build.py", line 71, in _do_build
    filename = build(td, {})
  File "/root/.local/lib/python3.7/site-packages/pep517/wrappers.py", line 216, in build_sdist
    'config_settings': config_settings,
  File "/root/.local/lib/python3.7/site-packages/pep517/wrappers.py", line 248, in _call_hook
    extra_environ=extra_environ
  File "/root/.local/lib/python3.7/site-packages/pep517/wrappers.py", line 57, in default_subprocess_runner
    check_call(cmd, cwd=cwd, env=env)
  File "/usr/local/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/python', '/root/.local/lib/python3.7/site-packages/pep517/_in_process.py', 'build_sdist', '/tmp/tmph3jvovmt']' returned non-zero exit status 1.
```

This is probably an easy check to catch if `git` doesn't exist before trying to use it? To fix this is a simple `apk --no-cache add git` before trying to run anything else.

**Comment by RonnyPfannschmidt** [comment] 2019-10-18 08:59
good find, this should check better

**Comment by ddelange** [comment] 2019-11-19 14:01
would be awesome if this can be a different error when git is not installed, took me a while before I figured this one out :)

**Comment by RonnyPfannschmidt** [comment] 2019-11-19 16:18
it should be, i'm currently not in a position to make the required amount of time for setuptools_scm, this likely changes next month

**Comment by matthijskooijman** [comment] 2020-05-04 08:47
Rather than checking if git exists, I would suggest trying to execute and treating the error that results from no installed git specially (Assuming `subprocess` can be made to throw some specific exception in this case, rather than just returning a non-zero exit code, which makes it indistinguishable from git returning the same exit code...).

**Comment by RonnyPfannschmidt** [comment] 2020-05-04 10:40
i think this one and #339 an collapse into a single action item

the plan would be to check tool existence in the tool triggered hooks and ensure detailed errors there
(something like a cli_tool_required helper)

**Comment by RonnyPfannschmidt** [comment] 2020-12-06 16:56
closing as duplicate of #339

**Closed as completed by RonnyPfannschmidt** 2020-12-06 16:56 UTC
Labels: bug

**Comment by SoundDesignerToBe** [comment] 2023-11-16 20:28
Took me hours of trial and error until I clicked on the link to this amazing solution: installing git on the image used in the CI pipeline
