### ISSUE TITLE
Support for git submodules

### ISSUE THREAD

**Issue by thmo** [pypa/setuptools-scm#96] opened 2016-08-15 19:31 UTC
A project `foo` that is checked out as a git submodule of another project, has a `.git` (a file!) that looks like this:

```
gitdir: ../.git/modules/foo
```

Now, when doing a `pip wheel .` in foo, everything gets copied to a fresh directory in `/tmp`, including the `.git` file, but as this carries a relative link, git fails, and subsequently setuptools_scm fails:

```
LookupError: setuptools-scm was unable to detect version for '/tmp/pip-8vKWxF-build'.
```

I am not sure if this is a wheel or a setuptools_scm problem, or both.

**Comment by RonnyPfannschmidt** [comment] 2016-08-15 20:13
definitively the combination of wheel/git - setuptools-scm cant do anything about that copy process itself, its bascially the victim

is there other metadata around?

**Comment by thmo** [comment] 2016-08-16 09:38
> is there other metadata around?

Not sure what you mean here.

**Comment by RonnyPfannschmidt** [comment] 2016-08-16 09:39
as in is there any way to figure whats wrong there

**Comment by thmo** [comment] 2016-08-16 09:41
You mean if the user is provided with enough information as to know what's going on? Not sure about that. The effects are somewhat similar to #77 and #81.

**Comment by thmo** [comment] 2016-08-16 09:55
Created a wheels ticket here: https://bitbucket.org/pypa/wheel/issues/173/support-for-git-submodules

**Comment by RonnyPfannschmidt** [comment] 2016-08-16 09:57
its not a bug in the wheel tool, is a bug in pip

**Comment by RonnyPfannschmidt** [comment] 2016-09-19 07:19
closing this one as breakage caused by a upstream project

**Closed as completed by RonnyPfannschmidt** 2016-09-19 07:19 UTC
