### ISSUE TITLE
version 3.0.5 does store 0.0.0 in its egg

### ISSUE THREAD

**Issue by scarabeusiv** [pypa/setuptools-scm#295] opened 2018-07-31 10:49 UTC
When building distribution package in openSUSE we have setuptools_scm declaring itself as 0.0.0.

Apart from that the package is building and passing all tests:
https://build.opensuse.org/package/show/devel:languages:python/python-setuptools_scm

This makes all the packages depending on setuptools_scm fail if they have some "minimal version" requirement.

**Comment by RonnyPfannschmidt** [comment] 2018-07-31 10:57
@scarabeusiv im unfamiliar with rpm specs and the related build processes, can you point me to the output of such a build process

**Comment by scarabeusiv** [comment] 2018-07-31 11:14
Here is the log: http://paste.opensuse.org/210969

Always the newest generated is below, but you would have to have an account:
https://build.opensuse.org/build/devel:languages:python/openSUSE_Tumbleweed/x86_64/python-setuptools_scm/_log

**Comment by scarabeusiv** [comment] 2018-07-31 11:15
The visible result there is:
```[   44s] Copying src/setuptools_scm.egg-info to /home/abuild/rpmbuild/BUILDROOT/python-setuptools_scm-3.0.5-17.1.x86_64/usr/lib/python3.6/site-packages/setuptools_scm-0.0.0-py3.6.egg-info```

**Comment by RonnyPfannschmidt** [comment] 2018-07-31 11:32
at first glance the metadata in the sdist is correct, i don't have access to any of the logs

**Comment by RonnyPfannschmidt** [comment] 2018-07-31 11:34
so this is either abug in setup.py or a bug in the rpm build, i will verify my suspicion about setup.py after im done with childcare ^^

**Comment by RonnyPfannschmidt** [comment] 2018-07-31 14:13
i can replicate the issue, it seems to be a bug of the easy_install sandbox

@jaraco it seems impossible to prevent - is there any way to avoid version 0 there

**Comment by RonnyPfannschmidt** [comment] 2018-07-31 14:36
it appears to be a duplicate of #137 running the installation twice fixes the metadata

**Comment by RonnyPfannschmidt** [comment] 2018-07-31 14:40
ok, something about the path handling is fishy
```
$ rm -f *.whl; PYTHONPATH=srwc pip wheel .;ls *.whl
Processing /home/rpfannsc/Projects/setuptools_scm_download/setuptools_scm-3.0.5
Building wheels for collected packages: setuptools-scm
  Running setup.py bdist_wheel for setuptools-scm ... done
  Stored in directory: /home/rpfannsc/Projects/setuptools_scm_download/setuptools_scm-3.0.5
Successfully built setuptools-scm
setuptools_scm-0.0.0-py2.py3-none-any.whl
(.egginstall) [rpfannsc@localhost setuptools_scm-3.0.5]$ rm -f *.whl; PYTHONPATH=src pip wheel .;ls *.whl
Processing /home/rpfannsc/Projects/setuptools_scm_download/setuptools_scm-3.0.5
Building wheels for collected packages: setuptools-scm
  Running setup.py bdist_wheel for setuptools-scm ... done
  Stored in directory: /home/rpfannsc/Projects/setuptools_scm_download/setuptools_scm-3.0.5
Successfully built setuptools-scm
setuptools_scm-3.0.5-py2.py3-none-any.whl
(.egginstall) [rpfannsc@localhost setuptools_scm-3.0.5]$ 
```

**Closed as completed** 2018-07-31 16:11 UTC
