### ISSUE TITLE
Wrong python code with chain assigning generated

### ISSUE THREAD

**Issue by olferuk** [pypa/setuptools-scm#910] opened 2023-09-20 12:00 UTC
My `pyproject.toml` requires libs timm==0.6.12 and InplaceABN==1.1.0 to be installed, and there are [these lines](https://github.com/mapillary/inplace_abn/blob/e89e59252ca67a09895f4e6dab4675bb3cf5c304/setup.py#L65C5-L65C20): 

```
   ...
    use_scm_version={
        "root": ".",
        "relative_to": __file__,
        "write_to": "inplace_abn/_version.py",
    },
    ...
```

With the setuptools_scm version 8.0.0 I got the following error in the generated code while importing timm (which relies on the inplace abn):

> import timm

```
E     File "/usr/local/lib/python3.10/dist-packages/inplace_abn/_version.py", line 4
E       __version__ : str = version : str = '1.1.0'
E                                   ^
E   SyntaxError: invalid syntax
```

**Comment by RonnyPfannschmidt** [comment] 2023-09-20 12:01
duplicate of #905 
affected release is yanked, bugfix release in 5s

**Closed as not planned by RonnyPfannschmidt** 2023-09-20 12:01 UTC

**Comment by olferuk** [comment] 2023-09-20 12:11
Wow, thank you! That was quick 😅
