### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by abhinavsingh** [pypa/setuptools-scm#908] opened 2023-09-20 11:35 UTC
Write to now seems to be producing invalid python files:

```
_scm_version.py", line 6
    __version__ : str = version : str = '1.3.0rc9.dev290+g7dce6a7'
                                ^
SyntaxError: invalid syntax
```

Previously we used to see

```
# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = '1.3.0rc9.dev289+g7451c8a.d20230920'
version_tuple = (1, 3, 0, 'dev289', 'g7451c8a.d20230920')
```

which then changed to:

```
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '1.3.0rc9.dev289+g7451c8a.d20230920'
__version_tuple__ = version_tuple = (1, 3, 0, 'dev289', 'g7451c8a.d20230920')
```

but since TODAY , we are seeing inclusion of typing syntax in generated files, leading to our workflow failures.   I tried to reproduce locally without any luck, on my local I don't see any typing information in generated files.

## Workaround
Pin to `setuptools-scm[toml] == 7.1.0`

**Comment by andrewmwilson** [comment] 2023-09-20 11:41
This is a duplicate of https://github.com/pypa/setuptools_scm/issues/905

**Comment by abhinavsingh** [comment] 2023-09-20 11:46
> This is a duplicate of #905

But we are seeing this for `python > 3.8`

**Closed as not planned** 2023-09-20 11:45 UTC
