### ISSUE TITLE
Cannot build package from a github download

### ISSUE THREAD

**Issue by pombredanne** [pypa/setuptools-scm#94] opened 2016-08-09 07:44 UTC
See https://github.com/django-guardian/django-guardian/issues/445
@brianmay wrote there:

> Yes, this is a known limitation in setuptools-scm. I would not recommend using development versions in this way; this is what releases are for.

There are many cases where 
- I cannot wait for some official release
- I do not have git installed on the installation machine

This is rather annoying.
Should this tools be avoided for git repos? 

Is the only way in these cases for a git-using lib using setuptools_scm to maintain a fork?

**Comment by RonnyPfannschmidt** [comment] 2016-08-09 10:35
if you need custom releases, just set up a devpi server and push sdists/wheels ?

**Comment by jaraco** [comment] 2016-08-09 11:53
Other options include setting up the project with a fallback version (so it still builds), working with github to inject the necessary metadata into downloads (last tag on the branch, distance from that tag, and hash of current head), or building a plugin that loads that metadata from github rather than relying on the info in the tar ball downloaded.

**Comment by pombredanne** [comment] 2016-08-09 12:22
@RonnyPfannschmidt you wrote:

> if you need custom releases, just set up a devpi server and push sdists/wheels ?

You are suggesting to replace a simple fetch from a URL by setting up a whole dedicated infrastructure? I am not sure this is worth it.

**Comment by pombredanne** [comment] 2016-08-09 12:23
@jaraco the idea of a fallback version makes makes a lot of sense. @brianmay what do you think?

**Comment by jaraco** [comment] 2016-08-09 13:35
See https://github.com/Crunch-io/pycrunch/pull/17, where I'm proposing using setuptools_scm for a project which has a similar use-case.

**Comment by pombredanne** [comment] 2016-08-09 15:27
@jaraco thanks . This is simple enough. I am still not sold with such a complex version number management process but I could live with a project of someone else using it this way at least ;) ... though the unknown version hardcoded would benefit to be updated to an actual meaningful version IMHO

**Comment by RonnyPfannschmidt** [comment] 2016-08-10 09:49
the process isnt complex - and mercurial can support tarballs just fine,

its simply that git is kind of crappy and has no way to include the relevant metadata in a meaningful way in the archive - its purely a git issue where git is very bad with metadata - and we cant fix it easily

**Comment by brianmay** [comment] 2016-08-15 09:11
@jaraco It looks like you solve the problem by using setuptools_scm_git_archive, correct?

https://pypi.python.org/pypi/setuptools_scm_git_archive

My reading of this is that github will substitute the version number in .git_archival.txt for any *.zip file download, and this will be used if setuptools_scm cannot get the version from git. Have I understood this correctly?

**Comment by RonnyPfannschmidt** [comment] 2016-08-15 09:18
the problem is, that it can only ever work correct for tags

**Comment by RonnyPfannschmidt** [comment] 2016-08-15 09:19
git has no way to make archives with a complete describe output embedded, its pretty much cripleing

**Comment by brianmay** [comment] 2016-08-15 10:00
@RonnyPfannschmidt In which case, can you explain the purpose of setuptools_scm_git_archive? What does it do?

**Comment by RonnyPfannschmidt** [comment] 2016-08-15 10:02
the implementor wanted support for downloading from git tags, that part works fine

if git ever gets sensible metadata it can be extended to support all downloads

but as is, git is simply broken by design and we cant help it

**Comment by RonnyPfannschmidt** [comment] 2016-08-16 09:57
closing this issue as broken upstream (git)

**Comment by anntzer** [comment] 2020-01-13 13:31
Is there any chance this can be reopened?  Support for github releases tarballs doesn't have to imply support for all downloads.  For example, setuptools_scm could still signal an error if it detects that the substituted .git_archive.txt doesn't appear to correspond to a git tag.

**Comment by RonnyPfannschmidt** [comment] 2020-01-13 13:42
@anntzer currently this is a opt-in by using the external plugin, im not entirely against re-adding this but for now i dont want to put in the work myself

**Comment by anntzer** [comment] 2020-01-13 14:08
I can work on a PR (or I don't know if @Changaco would want to do it? :-)), I just wanted to make sure it had a chance to get in.

**Comment by RonnyPfannschmidt** [comment] 2020-05-02 17:45
@anntzer can we consider this one reasonably solved with #410 ?

**Comment by anntzer** [comment] 2020-05-02 17:51
I would think so.

**Comment by RonnyPfannschmidt** [comment] 2020-05-02 18:35
Thanks

**Closed as completed by RonnyPfannschmidt** 2020-05-02 18:35 UTC
Labels: enhancement, help wanted, question

**Comment by pombredanne** [comment] 2020-05-03 16:04
> @anntzer can we consider this one reasonably solved with #410 ?

neat, let me try this! I had stopped using `setuptools_scm` because of this ticket and built instead this https://github.com/nexB/scancode-toolkit/blob/794c7f161a41730e569fa96ee06ad05a46d543d0/setup.py#L19 where I have a fallback to a default version, so I can build from a download or checkout
