### ISSUE TITLE
Allow setting `local_scheme` to `no-local-version` via an environment variable

### ISSUE THREAD

**Issue by abhilash1in** [pypa/setuptools-scm#478] opened 2020-09-16 05:09 UTC
I'm trying to enable CI/CD on a package such that my GitHub Actions workflow deploys to Test PyPi on every push. Example [here](https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#publishing-the-distribution-to-pypi-and-testpypi).

I would like to keep the default value for `local_scheme` in my repo and not use `no-local-version` to reap all the benefits it provides.

My deployments to production PyPI don't have a problem since that workflow is triggered only for a new tag/release (`no distance and clean`) and there is no local_scheme part (thus, compatible with PyPI).

However, during a `distance and clean` scenario for a push, the setuptools-scm generated version includes a `+{scm letter}{revision hash}` local_scheme part which is not compatible with PyPI.

Please provide a way to set `local_scheme ` to `no-local-version` via an environment variable so that the version generated during my CI build is compatible with PyPI and I can continuously deploy to Test PyPI (without having to create a new tag with each push).

I tried writing `local_scheme = "no-local-version"` to pyproject.toml file dynamically during a CI build (using `sed`) so that I can get a version number compatible with PyPI, however, the downside is that during a `no distance and clean` scenario, when I modify the pyproject.toml file, it becomes a `no distance and not clean` scenario which again generates a version number incompatible with PyPI. Moreover, with this approach, I will never get a pure SemVer version (`X.Y.Z`) without `.dev0` since I'm always modifying pyproject.toml and making it dirty.

**Comment by abhilash1in** [comment] 2020-09-16 06:40
My current workaround is to use a Python script in my GitHub CI workflow as follows:
```
- name: Set a PyPI compatible setuptools_scm pretend version
  # Required for continuously deploying to Test PyPI when we have commits not part of a tag/release
  # See https://github.com/pypa/setuptools_scm/issues/478
  run: |
    from setuptools_scm import get_version
    real_version = get_version()
    pretend_version = get_version(local_scheme='no-local-version')
    if pretend_version != real_version:
      print(f'Setting SETUPTOOLS_SCM_PRETEND_VERSION to {pretend_version} instead of using version {real_version}')
      print(f'::set-env name=SETUPTOOLS_SCM_PRETEND_VERSION::{pretend_version}')
    else:
      print(f'Version {real_version} is compatible with PyPI. No action needed.')
  shell: python
``` 
Apart from being a little hacky, this workaround also means I would need `setuptools_scm` installed before the actual build. In a normal scenario, the build system would automatically install `setuptools_scm` as a build dependency because of the "[build-system] requires" part in `pyproject.toml` file.

Would be great to have a simpler alternative!

For example, setting environment variable `SETUPTOOLS_SCM_LOCAL_SCHEME=no-local-version` should be able to replace the above behavior.

**Comment by RonnyPfannschmidt** [comment] 2020-11-29 21:08
closing as duplicate of #455

**Closed as completed by RonnyPfannschmidt** 2020-11-29 21:08 UTC
