### ISSUE TITLE
Failing test on Debian because of a not-closed file

### ISSUE THREAD

**Issue by SnarkBoojum** [pypa/setuptools-scm#401] opened 2020-01-22 15:40 UTC
I had taken a commit (e143a6cdb1e6a06bb79b1c9e9af4bb4b544cabfc) in Debian, which was fixing a problem with the tests.

Version 3.4.2 has been modified since this commit, and the problem is back, so I have a patch against that version to get through.

I'll attach it in a comment.

**Comment by SnarkBoojum** [comment] 2020-01-22 15:41
[clean_file_close.txt](https://github.com/pypa/setuptools_scm/files/4098109/clean_file_close.txt)

**Comment by RonnyPfannschmidt** [comment] 2020-01-22 20:47
duplicate of #400

**Closed as completed by RonnyPfannschmidt** 2020-01-22 20:47 UTC
