### ISSUE TITLE
setuptools_scm file finder should do nothing unless explicitly enabled

### ISSUE THREAD

**Issue by allisonkarlitskaya** [pypa/setuptools-scm#847] opened 2023-05-11 09:08 UTC
We're developing a Python package as part of a larger package ([cockpit-project/cockpit](https://github.com/cockpit-project/cockpit/)) containing code in other languages (mostly C and Javascript).  Part of our build process involves creating an sdist of the Python parts.

I was pretty surprised to find out recently that my sdists started containing all of the files from the entire version control.  I use `setuptools_scm` in some of my other projects but never considered (or desired) to use it with Cockpit.  There's no mention of `setuptools_scm` in either `pyproject.toml` or `setup.cfg` there.

It turns out that the mere act of *installing* the `setuptools_scm` package from the package manager is enough to globally affect the behaviour of all setuptools-using packages.  That's pretty unexpected.

I verified that removing `setuptools_scm` (and doing nothing else) stopped the files from being included.

At the very least: merely having setuptools_scm installed ought to be a no-op unless there's some specific mention of it in pyproject.toml (in the build requires, for example).  More ideally, it would switch this file-inclusion behaviour on the presence of the `[tool.setuptools_scm]` section, as is done for the version behaviour.

Thanks for your consideration!

**Comment by RonnyPfannschmidt** [comment] 2023-05-11 09:12
Currently setuptools does not provide a safe opt out,

**Comment by RonnyPfannschmidt** [comment] 2023-05-19 09:45
closing as duplicate of #561

**Closed as not planned by RonnyPfannschmidt** 2023-05-19 09:45 UTC
