### ISSUE TITLE
setuptools_scm is used even if not asked for

### ISSUE THREAD

**Issue by pavoljuhas** [pypa/setuptools-scm#208] opened 2018-01-09 06:50 UTC
The README file states that setuptools_scm is activated with a `setup_requires=['setuptools_scm']` argument to the `setup()` function.  I have however noticed that the file finder from setuptools_scm is active even if setuptools_scm is not mentioned in setup.py at all.

I have created a dummy git repository with the following files:
`MANIFEST.in`, `foo.py`, `sdist-include.txt`, `sdist-exclude.txt`, `setup.py`.
The MANIFEST.in contains a single line 
```
include sdist-include.txt
```

The `setup.py` looks as follows

```python
from setuptools import setup
setup(
    name='foo',
    py_modules=['foo'],
    version='1.0',
)
```

When `setuptools_scm` is not installed, the `sdist-exclude.txt` file is not present in the sdist distribution.  However, when `setuptools_scm` is available the `sdist-exclude.txt` is added to the sdist tarball.  I see this behavior with setuptools 36.5.0 and setuptools-scm 1.15.6.

I am not sure if this is a problem of setuptools or setuptools_scm, but I feel a mere presence of the setuptools_scm package should not change what gets packaged and what not.

**Comment by RonnyPfannschmidt** [comment] 2018-01-09 09:21
this bug is a unintended side-effect of the file finding mechanism setuptools uses - unfortunately setuptools plugins are not limited to what's listed in setup_requires, but all installed are loaded,

in addition a file finder never gets access to theconfiguration of a distribution, so its impossible to sanely manage opt-in/out

@jaraco any suggestions for resolving this?

**Comment by jaraco** [comment] 2018-01-20 14:59
I'd say this isn't an issue with setuptools_scm, but with setuptools itself in that setuptools is designed to use any and all file finders installed.

This behavior has essentially been a non-issue because the recommended use case for these libraries supplying file finders is to specify them as setup_requires such that they are only installed when needed.

I'd rather not go into more discussion here, as the issue is with the framework and not with setuptools_scm itself, which is properly implemented according to the design.

**Closed as completed by jaraco** 2018-01-20 14:59 UTC
