### ISSUE TITLE
Bundle setuptools_scm to avoid extra dependency?

### ISSUE THREAD

**Issue by cdeil** [pypa/setuptools-scm#140] opened 2017-01-06 22:58 UTC
Is it possible to bundle setuptools_scm to avoid an extra dependency?

Can you please answer this question in the docs?

It's a bit crazy, to have an extra dependency and ~ 10 files just to set a version number for a Python package, no?

Personally I'd prefer to have a single file I can bundle with my project, instead of an extra dependency.

**Comment by RonnyPfannschmidt** [comment] 2017-01-07 08:48
The Python ecosystem has no good tools to do this in a automatable manner, 

Since these days its reasonably painless to use this as is I opted out of inventing one

I wouldn't mind using a reasonable solution made by someone else, but its a really hairy problem

**Comment by cdeil** [comment] 2017-01-07 22:41
@RonnyPfannschmidt -  I don't really understand what you mean. Could you please elaborate?

Is it currently possible to drop the `setuptools_scm` in my repo and import from there, instead of having it as a dependency?

Would it be possible to just put all code (650 lines) in a single file to make bundling easier?
(Of course, if you find it's not worth the messy way to maintain the code in a single file to support that, fine, it's just a question.)
```
$ wc -l setuptools_scm/*
     130 setuptools_scm/__init__.py
      12 setuptools_scm/__main__.py
      13 setuptools_scm/discover.py
     106 setuptools_scm/git.py
      13 setuptools_scm/hacks.py
      74 setuptools_scm/hg.py
      41 setuptools_scm/integration.py
     109 setuptools_scm/utils.py
     152 setuptools_scm/version.py
     650 total
```

Is moving this into `setuptools` itself an option / is it planned?

---

I guess I'm mostly looking for explanatory additions to your docs here.
If you don't think this ticked / discussion is useful, feel free to close any time.

**Comment by RonnyPfannschmidt** [comment] 2017-01-07 22:55
@cdeil setuptools_scm uses setuptools features to determine the supported scms/fallbacks, just dumping some files somewhere would break that

pushing it directly into setuptools is also not planned since that would massively couple backward compatibility and release time-framing

possible quick hack solutions would be to just dump a wheel file into the project and adding it to the site dirs

generally it looks preferable to move torwards using pep518

**Comment by jaraco** [comment] 2017-01-15 17:25
+1 to focusing our energy on [pep 518](https://www.python.org/dev/peps/pep-0518/)

**Comment by RonnyPfannschmidt** [comment] 2017-01-16 09:19
im closing this one as wont-fix, since setuptools_scm shouldn't solve the issue, 
on that note, i'd be more than happy to include a 3rd party solution that just works
(preferably submitted as pull request since personally i dont want to spend more than review and a thumbs up on it)

**Closed as completed by RonnyPfannschmidt** 2017-01-16 09:19 UTC
Labels: enhancement, wontfix

**Comment by anntzer** [comment] 2017-11-10 23:18
Unless I am mistaken, putting the setuptools_scm egg into e.g. `/vendor/` and adding
```
[easy_install]
allow_hosts = ''  # (if you have no other setup_requires)
find_links = vendor
```
to your setup.cfg works.

**Comment by RonnyPfannschmidt** [comment] 2017-11-11 08:41
@anntzer that would however require to put the eggs for all python versions in (since setuptools doesn't support wheels at the moment)

**Comment by anntzer** [comment] 2017-11-11 09:24
I think that you can get away with a single egg that does not include the python version in the filename?  (and possibly remove the pyc's if you want?).  The spec says the python version is optional (http://setuptools.readthedocs.io/en/latest/formats.html#filename-embedded-metadata) and the same egg can be used across all versions (well all versions that setuptools_scm supports, which is good enough for me...).

**Comment by RonnyPfannschmidt** [comment] 2017-11-11 13:20
@anntzer i'd happyly accept patches that carry along the python version independent egg building and a script for including one in sdists if that works as intended

**Comment by anntzer** [comment] 2017-11-11 19:34
You may know that there is a fairly big taboo against using setup_requires in the scientific python community because the obvious thing to do is to setup_require numpy (because many extension modules depend on the numpy headers), but that would fetch an egg and build numpy from source, which 1) takes a *lot* of time, and 2) can introduce binary compatibility problems vs the system version.  Also there are other packages that are just not egg-able, because the headers would be not installed properly (cysignals, pybind11).

In this case, versioneer is nice, because it essentially just includes a script to vendor itself.

I am in the middle of switching my projects from versioneer to setuptools_scm *only* because I realized that I can use setup.cfg to force local resolution (so advertising this solution *may* entice more people to use setuptools_scm), and that I think setuptools_scm's configuration is better (plus, I prefer checking in a single egg rather than two huge files (versioneer.py and _version.py) which are slightly harder to keep up to date.

On the other hand I don't have any plans to muck around eggs more than needed...

**Comment by RonnyPfannschmidt** [comment] 2017-11-12 09:12
@anntzer personally im waiting for stuff like PEP-517/518 because those make pure python dependencies for the build time massively simpler

whats indded is an issue is the binary dependencies of scientific packages - i hope that given a pep-517/8 kinda toolset they get enabled to take a more controlled approach (but right now its not that nice)
