### ISSUE TITLE
setuptools_scm 8.0.1 fails to compile with --no-binary :all:

### ISSUE THREAD

**Issue by BaconRanch** [pypa/setuptools-scm#920] opened 2023-09-20 20:18 UTC
I believe the issue here: https://github.com/pypa/setuptools_scm/issues/722 is now a problem again as of 8.0.1.

When I run `pip install "setuptools_scm[toml]==8.0.1" --no-binary :all:` it fails with the same recursion error as in the original issue.
When I run `pip install "setuptools_scm[toml]==7.1.0" --no-binary :all:` it installs with no issues.

Just like in the original issue, I tested using Python 3.9 (and also, in my case specifically, pip 23.2.1):
```
 Collecting setuptools_scm[toml]==8.0.1
   Downloading setuptools-scm-8.0.1.tar.gz (71 kB)
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.8/71.8 kB 5.1 MB/s eta 0:00:00
   Installing build dependencies: started
   Installing build dependencies: finished with status 'error'
   error: subprocess-exited-with-error

   × pip subprocess to install build dependencies did not run successfully.
   │ exit code: 1
   ╰─> [79 lines of output]
       Ignoring typing_extensions: markers 'python_version < "3.8"' don't match your environment
       Collecting importlib-metadata>=4.6
         Downloading importlib_metadata-6.8.0.tar.gz (53 kB)
            ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.5/53.5 kB 3.5 MB/s eta 0:00:00
         Installing build dependencies: started
         Installing build dependencies: finished with status 'error'
         error: subprocess-exited-with-error

         × pip subprocess to install build dependencies did not run successfully.
         │ exit code: 2
         ╰─> [58 lines of output]
             Collecting setuptools>=56
               Downloading setuptools-68.2.2.tar.gz (2.2 MB)
                  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 13.9 MB/s eta 0:00:00
               Getting requirements to build wheel: started
               Getting requirements to build wheel: finished with status 'done'
               Installing backend dependencies: started
               Installing backend dependencies: finished with status 'done'
               Preparing metadata (pyproject.toml): started
               Preparing metadata (pyproject.toml): finished with status 'done'
             Collecting setuptools_scm[toml]>=3.4.1
               Using cached setuptools-scm-8.0.1.tar.gz (71 kB)
             ERROR: Exception:
             Traceback (most recent call last):
               File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
                 status = run_func(*args)
               File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
                 return func(self, options, args)
               File "/usr/local/lib/python3.9/dist-packages/pip/_internal/commands/install.py", line 377, in run
                 requirement_set = resolver.resolve(
               File "/usr/local/lib/python3.9/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
                 result = self._result = resolver.resolve(
               File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
                 state = resolution.resolve(requirements, max_rounds=max_rounds)
               File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
                 self._add_to_criteria(self.state.criteria, r, parent=None)
               File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
                 if not criterion.candidates:
               File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
                 return bool(self._sequence)
               File "/usr/local/lib/python3.9/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
                 return any(self)
               File "/usr/local/lib/python3.9/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
                 return (c for c in iterator if id(c) not in self._incompatible_ids)
               File "/usr/local/lib/python3.9/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
                 candidate = func()
               File "/usr/local/lib/python3.9/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
                 self._link_candidate_cache[link] = LinkCandidate(
               File "/usr/local/lib/python3.9/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 293, in __init__
                 super().__init__(
               File "/usr/local/lib/python3.9/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
                 self.dist = self._prepare()
               File "/usr/local/lib/python3.9/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
                 dist = self._prepare_distribution()
               File "/usr/local/lib/python3.9/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution
                 return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
               File "/usr/local/lib/python3.9/dist-packages/pip/_internal/operations/prepare.py", line 538, in prepare_linked_requirement
                 return self._prepare_linked_requirement(req, parallel_builds)
               File "/usr/local/lib/python3.9/dist-packages/pip/_internal/operations/prepare.py", line 653, in _prepare_linked_requirement
                 dist = _get_prepared_distribution(
               File "/usr/local/lib/python3.9/dist-packages/pip/_internal/operations/prepare.py", line 68, in _get_prepared_distribution
                 with build_tracker.track(req):
               File "/usr/lib/python3.9/contextlib.py", line 117, in __enter__
                 return next(self.gen)
               File "/usr/local/lib/python3.9/dist-packages/pip/_internal/operations/build/build_tracker.py", line 122, in track
                 self.add(req)
               File "/usr/local/lib/python3.9/dist-packages/pip/_internal/operations/build/build_tracker.py", line 92, in add
                 raise LookupError(message)
             LookupError: https://files.pythonhosted.org/packages/a7/16/8aef42ae27036ceb201f1774940357da18ae7daac45bdd721da554892012/setuptools-scm-8.0.1.tar.gz (from https://pypi.org/simple/setuptools-scm/) (requires-python:>=3.8) is already being built: setuptools_scm[toml]==8.0.1 from https://files.pythonhosted.org/packages/a7/16/8aef42ae27036ceb201f1774940357da18ae7daac45bdd721da554892012/setuptools-scm-8.0.1.tar.gz
             [end of output]

         note: This error originates from a subprocess, and is likely not a problem with pip.
       error: subprocess-exited-with-error

       × pip subprocess to install build dependencies did not run successfully.
       │ exit code: 2
       ╰─> See above for output.

       note: This error originates from a subprocess, and is likely not a problem with pip.
       [end of output]

   note: This error originates from a subprocess, and is likely not a problem with pip.
 error: subprocess-exited-with-error

 × pip subprocess to install build dependencies did not run successfully.
 │ exit code: 1
 ╰─> See above for output.

 note: This error originates from a subprocess, and is likely not a problem with pip.
 
```

**Comment by DnPlas** [comment] 2023-09-21 07:19
We are having the same issue #918

**Comment by RonnyPfannschmidt** [comment] 2023-09-21 07:31
closing this as dupe of #918

it may be necesary to vendor part of importlib_metadata :/

**Closed as not planned by RonnyPfannschmidt** 2023-09-21 07:31 UTC
