### ISSUE TITLE
relative "write_to" doesn't work properly on non-root projects

### ISSUE THREAD

**Issue by pitrou** [pypa/setuptools-scm#304] opened 2018-08-09 16:22 UTC
When a project is in a subdir of a git repository, and it specifies a relative "write_to" option, either those two things will fail:
- installing directly from the project directory (e.g. `python setup.py develop`)
- installing from a source distribibution (e.g. `python setup.py sdist && pip install dist/...`)

It seems that the rule for computing the target path to write to handles the path to root directory differently in those two cases.

The workaround right now is to compute an absolute path for "write_to" ourselves, see https://github.com/apache/arrow/pull/2415/files

**Comment by RonnyPfannschmidt** [comment] 2018-08-10 09:28
indeed, this oversight is a masive problem, i just finished reviewing the details, and the support for sdist install vs repo install is mismatched

it's going to take a while to sort the structure of the handling of the paths out - and will likely require  a major release to sort it out right

**Comment by anntzer** [comment] 2018-08-16 19:44
Seems related to https://github.com/pypa/setuptools_scm/issues/188.

**Comment by RonnyPfannschmidt** [comment] 2023-02-24 09:51
closing as duplicate of #188

**Closed as completed by RonnyPfannschmidt** 2023-02-24 09:51 UTC
Labels: bug
