### ISSUE TITLE
no-local-version on release branches

### ISSUE THREAD

**Issue by pmeier** [pypa/setuptools-scm#462] opened 2020-07-10 08:59 UTC
I'm using `releases/*` branches to check if my package is publishable on PyPI or not. Amongst others, I try to upload to TestPyPI. 

The problem I'm facing is that even with `version_scheme="release-branch-semver"` all commits up to a tag are marked as development commit. Since they include a local identifier the upload is rejected. This is resolved after I create the tag, but I can't know beforehand if the upload will be rejected for another reason than the version.

My current workaround is to pre-install `setuptools_scm` and use `get_version(version_scheme="release-branch-semver", local_scheme="no-local-version")` to set `SETUPTOOLS_SCM_PRETEND_VERSION`. 

Would it be possible to add a `local_scheme` that uses `no-local-version` while on a `release/*` branch and otherwise behaves as the default?

**Comment by RonnyPfannschmidt** [comment] 2020-07-10 12:27
It would be possible, my proposal however would be to have a env var which generally allows informed release pipelines to opt out of dev/local version tags to allow test artifact upload

**Comment by RonnyPfannschmidt** [comment] 2020-11-29 21:09
closing as duplicate of #455 given the proposal will add a general env var for config overrides

**Closed as completed by RonnyPfannschmidt** 2020-11-29 21:09 UTC
