### ISSUE TITLE
write_to= in monorepo

### ISSUE THREAD

**Issue by dabljues** [pypa/setuptools-scm#788] opened 2022-11-26 12:54 UTC
Hi. Let's say I have a dir structure like this:

```sh
├── backend/
│   ├── src/
│   │   ├── foo/
│   ├── setup.cfg
│   ├── pyproject.toml
├── frontend/
```

So, I have a project named `foo`, which has a `backend` and `frontend` dirs. Backend is python, the package name is `foo`.

What I want to do is to use `setuptools_scm` in my backend app. The problem is, the `.git` folder is in the project's root, so one dir above `backend`. To solve this I have to provide a `root` option to my `setuptools_scm` configuration:

```toml
[tool.setuptools_scm]
write_to = "./src/foo/version.py"
write_to_template = """\
# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = \"{version}\"
"""
root = ".."
```

I use `write_to`, because I do `from foo.version import __version__` to use it in various places (i.e. initializing `FastAPI` or loggers).

Now, there's a problem:

```sh
  File "/home/dabljues/projects/foo/backend/.tox/.package/lib/python3.10/site-packages/setuptools_scm/__init__.py", line 78, in dump_version
    with open(target, "w") as fp:
FileNotFoundError: [Errno 2] No such file or directory: '../src/foo/version.py'
```

When I don't use `write_to`, then it works, but I won't have a `version.py` file generated to later import it in code.

Is there something I am doing wrong? Can I somehow use `setuptools_scm` like this (meaning with `write_to`) in a monorepo like above?

**Comment by effigies** [comment] 2022-12-05 17:47
Seems related to #188 and #304.

I'm also running into this issue trying to use `write_to` in a non-root project. I'm exploring dropping versioneer for setuptools_scm, and this is the main blocker I've found so far.

**Comment by effigies** [comment] 2023-01-05 19:45
Turns out that you can do this with [hatch-vcs](https://github.com/ofek/hatch-vcs), if you're willing to move away from setuptools.

**Comment by RonnyPfannschmidt** [comment] 2023-02-24 09:52
closing as duplicate of #188

**Closed as completed by RonnyPfannschmidt** 2023-02-24 09:52 UTC
