### ISSUE TITLE
Version in wheel names for win are broken

### ISSUE THREAD

**Issue by FrancescAlted** [pypa/setuptools-scm#1071] opened 2024-08-28 18:23 UTC
We have recently modernized the build system, and adopted [scikit-build-core](https://github.com/scikit-build/scikit-build-core) for our [python-blosc2 project](https://github.com/Blosc/python-blosc2). In the process of doing that, we took the opportunity to use [setuptools-scm](https://github.com/Blosc/python-blosc2/blob/main/pyproject.toml#L75) for dynamically building version numbers.

However, when trying to do a release of python-blosc2, we [recently found](https://github.com/Blosc/python-blosc2/issues/247) that some of the wheels for Windows were produced with non-valid version numbers for uploading to PyPI.  Curiously enough, this only affects to Windows, whereas Linux (both x86_64 and aarch64) and Mac (also x86_64 and arm64) are completely fine.

Can anyone shed some light here? Thanks in advance.

**Comment by RonnyPfannschmidt** [comment] 2024-08-28 20:08
closing this a works as intended, the upstrem issue shows that unplanned file changes happen

**Closed as completed by RonnyPfannschmidt** 2024-08-28 20:08 UTC
